name: cdk

on:
  push:
    branches:
        - master
  pull_request:
jobs:
  aws_cdk:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: npm upgrade
        working-directory: ./lambda
        run: npm install -g npm

      - name: npm version
        working-directory: ./lambda
        run: npm --version

      - name: Setup dependencies
        working-directory: ./lambda
        run: npm install

      - name: Setup build
        working-directory: ./lambda
        run: npm run build

      - name: Unit tests
        working-directory: ./lambda
        if: contains(github.event_name, 'pull_request')
        run: npm run test
          
      - name: CDK Diff Check
        working-directory: ./lambda
        if: contains(github.event_name, 'pull_request')
        run: npx cdk diff
        env:
          AWS_DEFAULT_REGION: 'ap-northeast-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: CDK Deploy
        working-directory: ./lambda
        if: contains(github.event_name, 'push')
        run: npx cdk deploy  --require-approval
        env:
          AWS_DEFAULT_REGION: 'ap-northeast-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
